services:
  zipkin-service:
    image: openzipkin/zipkin
    ports:
      - 9411:9411

  config-server:
    build: ./config-server
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    ports:
      - 9411:9411

  eureka-server:
    build: ./eureka-server
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 25s
    depends_on:
      config-server:
        condition: service_healthy
    ports:
      - 8761:8761

  api-gateway:
    build: ./api-gateway
    healthcheck:
      test: "curl --fail --silent localhost:8000/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 60s
    depends_on:
      eureka-server:
        condition: service_healthy
    ports:
      - 8000:8000

  consumer-service:
    build: ./consumer-service
    depends_on:
      eureka-server:
        condition: service_healthy

  producer-service:
    build: ./producer-service
    depends_on:
      eureka-server:
        condition: service_healthy